#############################################################
## JOB DESCRIPTION                                         ##
#############################################################

# Equilibration in NVT ensemble of 
# 2PYP in a Water Box


#############################################################
## ADJUSTABLE PARAMETERS                                   ##
#############################################################

structure          ./2PYP_ionized.psf
coordinates        ./2PYP_ionized.pdb
bincoordinates     ./2PYP_minimize2.coor
extendedSystem     ./2PYP_minimize2.xsc


numsteps 50000 # 100 ps

temperature         0

set outputname     2PYP_NVT


#############################################################
## SIMULATION PARAMETERS                                   ##
#############################################################

# Input
paraTypeCharmm	    on
parameters          ./par_all27_prot_lipid.inp 

# Force-Field Parameters
exclude             scaled1-4
1-4scaling          1.0
cutoff              12.0
switching           on
switchdist          10.0
pairlistdist        14.0


# Integrator Parameters
timestep            2.0  ;# 2fs/step
rigidBonds          all  ;# needed for 2fs steps
nonbondedFreq       1
fullElectFrequency  2  
stepspercycle       10


# Constant Temperature Control
langevin            on    ;# do langevin dynamics
langevinDamping     5     ;# damping coefficient (gamma) of 1/ps
langevinTemp        300
langevinHydrogen    off    ;# don't couple langevin bath to hydrogens


wrapAll on


# PME (for full-system periodic electrostatics)
PME                 yes
PMEGridSpacing      1.0

#manual grid definition
#PMEGridSizeX        45
#PMEGridSizeY        45
#PMEGridSizeZ        48


#off (NVT)

langevinPiston        off
langevinPistonTarget  1.01325 ;#  in bar -> 1 atm
langevinPistonPeriod  200.0
langevinPistonDecay   100.0
langevinPistonTemp    300

constraints on
consRef     2PYP_constraints.pdb
consKFile   2PYP_constraints.pdb
consKCol     B
constraintScaling       10.0


# Output
outputName          $outputname

restartfreq         500    ;# 500steps = every 1ps
dcdfreq             500
xstFreq             500
outputEnergies      500
outputPressure      500
outputTiming        500

#############################################################
## EXTRA PARAMETERS                                        ##
#############################################################


#############################################################
## EXECUTION SCRIPT                                        ##
#############################################################


